framework:
    cache:
        prefix_seed: microjersey
        app: cache.adapter.filesystem
        # Redis
        #        app: cache.adapter.redis
        #        default_redis_provider: '%env(resolve:REDIS_URL)%'

        # APCu (not recommended with heavy random-write workloads as memory fragmentation can cause perf issues)
    #app: cache.adapter.apcu

when@dev:
    framework:
        cache:
            app: cache.adapter.filesystem
    #            app: cache.adapter.null

    services:
        cache.adapter.null:
            class: Symfony\Component\Cache\Adapter\NullAdapter
