# Read the documentation at https://github.com/thephpleague/flysystem-bundle/blob/master/docs/1-getting-started.md
flysystem:
    storages:
        storage.default:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%%/public/storage/default'
        storage.jerseys:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/public/storage/jerseys'
        storage.clubs:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/public/storage/clubs'

#when@prod:
#    services:
#        digitalocean_spaces_client:
#            #            class: 'AsyncAws\S3\S3Client'
#            arguments:
#                -   endpoint: '%env(DIGITALOCEAN_SPACES_ENDPOINT)%'
#                    accessKeyId: '%env(DIGITALOCEAN_SPACES_ID)%'
#                    accessKeySecret: '%env(DIGITALOCEAN_SPACES_SECRET)%'
#    flysystem:
#        storages:
#            storage.jerseys:
#                adapter: 'asyncaws'
#                options:
#                    client: 'digitalocean_spaces_client'
#                    bucket: '%env(DIGITALOCEAN_SPACES_BUCKET)%'
