twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        brand: '%brand%'
        brand_html: '%brand_html%'
    form_themes: [ 'form/bare.html.twig' ]

when@test:
    twig:
        strict_variables: true
