# https://symfony.com/doc/current/templates.html#rendering-a-template-directly-from-a-route
app_stimulus:
  path: /stimulus
  defaults:
    _controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    template: stimulus.html.twig

app:
  resource:
    path: ../src/Controller/App
    namespace: App\Controller\App
  name_prefix: 'app.'
  type: attribute

admin:
  prefix: /admin
  resource:
    path: ../src/Controller/Admin
    namespace: App\Controller\Admin
  name_prefix: 'admin.'
  type: attribute

auth:
  resource:
    path: ../src/Controller/Auth
    namespace: App\Controller\Auth
  name_prefix: 'auth.'
  type: attribute
