# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    # System parameters: https://symfony.com/doc/current/performance.html
    .container.dumper.inline_factories: true

    brand: 'MicroJersey'
    brand_html: '<b>Micro</b>Jersey 🎶'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

